"""Reviewer agent - reviews code for quality and bugs."""
from .base import BaseAgent, AgentState
from langchain_core.messages import HumanMessage


REVIEWER_SYSTEM_PROMPT = """You are a Code Review Agent, an expert at reviewing code for quality, security, and best practices.

Your responsibilities:
1. Review code for bugs and issues
2. Check for security vulnerabilities
3. Ensure code follows best practices
4. Verify proper error handling
5. Check code readability and maintainability
6. Suggest improvements

Review criteria:
- Code correctness and logic
- Security vulnerabilities
- Error handling
- Performance considerations
- Code organization
- Documentation

Output format:
- Provide a detailed review report
- Rate issues by severity: CRITICAL, HIGH, MEDIUM, LOW
- Provide specific, actionable recommendations
- Final verdict: APPROVED or NEEDS_REVISION"""


class ReviewerAgent(BaseAgent):
    """Agent responsible for reviewing code."""

    def __init__(self, model_name: str = "gpt-4o", temperature: float = 0.3):
        super().__init__(
            name="Reviewer",
            role="Code Reviewer",
            system_prompt=REVIEWER_SYSTEM_PROMPT,
            model_name=model_name,
            temperature=temperature,
        )

    def process(self, state: AgentState) -> AgentState:
        """Review the code generated by the Coder."""
        code = state.artifacts.get("code", "")

        if not code:
            state.errors.append("No code to review")
            state.status = "failed"
            return state

        prompt = f"""Please review the following code:

```{code}
```

Provide a comprehensive review. If there are issues, clearly indicate what needs to be fixed.
Final verdict must be APPROVED or NEEDS_REVISION."""

        response = self.chain.invoke(
            {
                "input": prompt,
                "chat_history": state.messages,
            }
        )

        state.artifacts["review"] = response.content
        state.messages.append(response)

        if "NEEDS_REVISION" in response.content.upper():
            state.status = "needs_revision"
        else:
            state.status = "approved"

        return state

